### ISSUE TITLE
unique urls so that people can share their own view

### ISSUE THREAD

**Issue by micahstubbs** [ssthouse/github-visualization#4]
would be really cool if we could add a `?user=micahstubbs` to the url so I could share a url like this:

https://ssthouse.github.io/github-visualization/#/main?user=micahstubbs

![screen shot 2018-05-14 at 12 26 22 pm](https://user-images.githubusercontent.com/2119400/40018961-af1c468a-5772-11e8-9c0f-b07b18e50a56.png)

**Comment by ssthouse** [comment]
hi, thank you for your suggestion!
I have finished this issue, please check :smiley:

**Comment by micahstubbs** [comment]
very nice 👏

**Comment by micahstubbs** [comment]
aaaand I tweeted it https://twitter.com/micahstubbs/status/996227574668775425

**Comment by ssthouse** [comment]
thank you so much for your sharing! :laughing:
